### ISSUE TITLE
WebUI call out for trigger mappings/configure not visible in Safari or Firefox

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#101]
In Safari or Firefox I cannot configure the trigger or map flow params from the trigger, as clicking the trigger does not yield the slide out menu.

**Comment by mellistibco** [comment]
Put another way, Chrome is the inly browser that actually works...

**Comment by lwlwlwlw** [comment]
Internet Explore 11 ( windows 10 1607 64bit) does not work as well.

Accessing http://flogoserver:3303 shows wait icon circling forever, with following error message in developer tool:

HTML1300: Navigation occurred.
35.194.174.162:3303
[Script Loader] TypeError: ,0 is not iterable!
   "[Script Loader]"
   {
      [functions]: ,
      __proto__: { },
      message: ",0 is not iterable!",
      name: "TypeError",
      stack: "TypeError: ,0 is not iterable!
   at t.exports (http://35.194.174.162:3303/polyfills.6e27e5a28bd70afae553.bundle.js:36:23099)
   at Anonymous function (http://35.194.174.162:3303/polyfills.6e27e5a28bd70afae553.bundle.js:1:5682)
   at Anonymous function (http://35.194.174.162:3303/polyfills.6e27e5a28bd70afae553.bundle.js:36:16596)
   at w (eval code:84:28)
   at Anonymous function (eval code:20:164)
   at eval code (eval code:5:3)
   at n.exports (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:543)
   at KsQ5 (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:174)
   at r (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:89)
   at Anonymous function (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:39)
   at r (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:89)
   at window.webpackJsonp (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:416)
   at Global code (http://35.194.174.162:3303/scripts.78ba"
   }

[Script Loader] TypeError: Unable to get property 'extend' of undefined or null reference
   "[Script Loader]"
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'extend' of undefined or null reference",
      message: "Unable to get property 'extend' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'extend' of undefined or null reference
   at Anonymous function (eval code:8:1309)
   at Anonymous function (eval code:8:181)
   at eval code (eval code:8:2)
   at n.exports (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:543)
   at K74v (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:131)
   at r (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:89)
   at Anonymous function (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:59)
   at r (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:89)
   at window.webpackJsonp (http://35.194.174.162:3303/inline.56f3088d691e6f9ed468.bundle.js:1:416)
   at Global code (http://35.194.174.162:3303/scripts.78baaf72a0205848f1de.bundle.js:1:1)"
   }

SCRIPT5007: Unable to get property 'apply' of undefined or null reference
vendor.8f3b251c2c3ffc756279.bundle.js (898,815)

**Comment by mellistibco** [comment]
@fcastill this has been resolved in the next release?

**Comment by fcastill** [comment]
@mellistibco yes, fixed for all major evergreen browsers: Chrome, Firefox, Safari and MS Edge

**Comment by mellistibco** [comment]
This is resolved in the latest flogo/flogo-docker:latest docker image.
