### ISSUE TITLE
Can't install activity from Web UI if code in branch

### ISSUE THREAD

**Issue by philippegabert** [TIBCOSoftware/flogo#155]
Hi, 

From my fork of the flogo-contrib repo, I have created a branch to work on a new activity.
I've tried to install this activity using the Web UI but the installation fails..

`2018-02-09T20:54:38.902Z - verbose: GET /i18n/fr.json - 0
2018-02-09T20:54:38.902Z - verbose:
2018-02-09T20:54:38.902Z - verbose:
[log] Install Activities
[ 'github.com/philippegabert/flogo-contrib/activity/histocompare' ]
[log] adding activities to test engine...
[info] Stop engine PID: 329, COMMAND: ./flogo-web, ARGUMENTS:
[info] Stop engine Process 329 has been killed!
[log] Install from GitHub
[ 'github.com/philippegabert/flogo-contrib/activity/histocompare' ]
2018-02-09T20:55:05.777Z - info: Exec command: flogo install github.com/philippegabert/flogo-contrib/activity/histocompare in local/engines/flogo-web
[info] run command: flogo install github.com/philippegabert/flogo-contrib/activity/histocompare
[log] command exited with code 1: flogo install github.com/philippegabert/flogo-contrib/activity/histocompare
FATAL: command "fetch" failed: lstat /tmp/flogo-web/build/server/gb-vendor-846607781/activity/histocompare: no such file or directory
FATAL: command "vendor" failed: exit status 1
FATAL: command "install" failed: exit status 1

[error] add activities to test engine
FATAL: command "fetch" failed: lstat /tmp/flogo-web/build/server/gb-vendor-846607781/activity/histocompare: no such file or directory
FATAL: command "vendor" failed: exit status 1
FATAL: command "install" failed: exit status 1

2018-02-09T20:55:09.623Z - error:  Error: [error] Encounter error to add activities to test engine.
    at Object.installActivities (/tmp/flogo-web/build/server/api/activities/index.js:145:13)
    at throw (native)
    at onRejected (/tmp/flogo-web/build/server/node_modules/co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

However, using the cli (not in the docker image but on my PC)
`flogo install github.com/philippegabert/flogo-contrib/activity/histocompare`
it works... 

After merging the branch into the master, then I can install the extension using the WebUI...

So... I guess that installing activities that are in branches is not working from the Web UI.

Philippe

**Comment by mellistibco** [comment]
@fcastill let's test if the switch to go dep resolves this
