### ISSUE TITLE
Running app in Lambda fails

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#191]
After creating my app and deploying it to AWS Lambda, it fails when running with the below error message:
```
2018-03-19 03:04:16.534 ERROR  [engine] - Engine: Error Creating trigger instances - Trigger Factory 'github.com/TIBCOSoftware/flogo-contrib/trigger/lambda' not registered
panic: Engine: Error Creating trigger instances - Trigger Factory 'github.com/TIBCOSoftware/flogo-contrib/trigger/lambda' not registered

goroutine 1 [running]:
lambda/vendor/github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Init(0xc42008c820, 0x8d0d01, 0xc42008c820, 0x0)
	/codebuild/output/src047367214/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/my-first-flogoapp/lambda/src/lambda/vendor/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:85 +0x8ab
main.init.0()
	/codebuild/output/src047367214/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/my-first-flogoapp/lambda/src/lambda/shim_support.go:98 +0xd7
```

The app is copied from the [docs](https://tibcosoftware.github.io/flogo/faas/how-to/)

**Comment by mellistibco** [comment]
Hi @retgits please update the cli, issue introduced solving another, related issue connected with the switch to go dep.

go get -u github.com/TIBCOSoftware/flogo-cli/...

**Comment by mellistibco** [comment]
@retgits did the update to the cli resolve this issue?

**Comment by retgits** [comment]
Ah sorry, I forgot to report back 😱 Yes, the issue is resolved with the new version of CLI.
