### ISSUE TITLE
Using REST activity in Go app

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#319]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[X] support request
[] general question
```

**Current behavior (how does the issue manifest):** I'm building Go apps that make use of several activities, one of them being the REST activity. When I look at the activity.json for the required fields, they should be `uri` and `method` so the below code should work to create a valid instance
```
// Call out to another service
	in = map[string]interface{}{"method": "GET", "uri": fmt.Sprintf("%s%s", paymentservice, id)}
	logger.Info(in)
	out, err = flogo.EvalActivity(&rest.RESTActivity{}, in)
	if err != nil {
		return nil, err
	}
``` 

When I run the code I see:
```
2018-07-25 11:17:51.573 INFO   [engine] - map[method:GET uri:http://localhost:9999/api/expected-date/1234]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1319087]

goroutine 22 [running]:
github.com/TIBCOSoftware/flogo-lib/flogo.EvalActivity(0x0, 0x0, 0xc420140f30, 0x3, 0xc42013da78, 0xc4200c4510)
        /Users/lstigter/go/src/github.com/TIBCOSoftware/flogo-lib/flogo/support.go:154 +0x77
main.handler(0x1432cc0, 0xc4200a2008, 0xc420140840, 0x20750c0, 0x1355401, 0xc420099470)
        /Users/lstigter/go/src/github.com/retgits/flogo-components/apps/invoiceservice-go/main.go:91 +0x972
github.com/TIBCOSoftware/flogo-lib/flogo.(*proxyAction).Run(0xc420098ef0, 0x1432cc0, 0xc4200a2008, 0xc420140840, 0xc420098ef0, 0x0, 0x0)
        /Users/lstigter/go/src/github.com/TIBCOSoftware/flogo-lib/flogo/support.go:139 +0x47
github.com/TIBCOSoftware/flogo-lib/engine/runner.ActionWorker.Start.func1(0x3, 0x1648208, 0xc42008e300, 0xc420132300, 0xc42008e360)
        /Users/lstigter/go/src/github.com/TIBCOSoftware/flogo-lib/engine/runner/worker.go:100 +0x8b4
created by github.com/TIBCOSoftware/flogo-lib/engine/runner.ActionWorker.Start
        /Users/lstigter/go/src/github.com/TIBCOSoftware/flogo-lib/engine/runner/worker.go:73 +0x5c
exit status 2
```

I'm sure I'm doing something wrong, but I can't find the issue 😢 

**Expected behavior:** I'd expect the REST activity to work

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** 0.5.5

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.5

**Comment by retgits** [comment]
My bad, I forgot to run `go generate` 😅
