### ISSUE TITLE
Tester Fails

### ISSUE THREAD

**Issue by MMashalkar** [TIBCOSoftware/flogo#337]
Occasionally, tester fails. After first failure, only option is to restart container. Here is a sample message
2018-08-10T01:50:51.519Z - verbose: POST /v1/api/flows/run/flows - 0
2018-08-10T01:50:51.519Z - verbose:  creationDate=2018-08-10 01:50:51.513497669 +0000 UTC m=+220.376587985, description=, id=1, name=MyFlow
2018-08-10T01:50:51.519Z - verbose:  name=MyFlow, description=, input=[name=Incoming, type=string, value=TEST], output=[name=Outgoing, type=string], name=MyFlow, model=tibco-simple, type=1, attributes=[], id=root, type=1, activityType=, ref=, name=root, tasks=[id=log_2, name=Log Message, description=Simple Log Activity, type=1, activityType=, activityRef=github.com/TIBCOSoftware/flogo-contrib/activity/log, attributes=[name=message, value=, required=false, type=string, name=flowInfo, value=false, required=false, type=boolean, name=addToFlow, value=false, required=false, type=boolean], inputMappings=[type=3, value=string.concat("GOT:", $flow.Incoming), mapTo=message, type=2, value=1, mapTo=addToFlow, type=2, value=1, mapTo=flowInfo], , id=mapper_3, name=Mapper, description=Simple Mapper Activity, type=1, activityType=, activityRef=github.com/TIBCOSoftware/flogo-contrib/activity/mapper, attributes=[name=mappings, value=[mapTo=Outgoing, type=1, value=$flow.Incoming], required=true, type=array], ], links=[id=1, from=log_2, to=mapper_3, type=0], id=__error_root, type=1, activityType=, ref=, name=error_root, tasks=[], links=[]
http-errors deprecated non-first-argument status code; replace with createError(500, ...) node_modules/koa/lib/context.js:89:23
2018-08-10T01:50:51.586Z - error:  InternalServerError: socket hang up
    at Object.throw (/tmp/flogo-web/build/server/node_modules/koa/lib/context.js:89:23)
    at Object.flowStart (/tmp/flogo-web/build/server/api/flows.run/index.js:597:15)
    at flowStart.throw (<anonymous>)
    at onRejected (/tmp/flogo-web/build/server/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by MMashalkar** [comment]
RHEL 7.3

**Comment by MMashalkar** [comment]
To replicate. Create a flow, with in input and an output
Add a log and a mapper. In Mapper, map input to output
Run Flow

**Comment by MMashalkar** [comment]
After first failure, all "Run Flow" result in same error:
2018-08-10T01:56:43.445Z - error:  InternalServerError: connect ECONNREFUSED 127.0.0.1:8080
    at Object.throw (/tmp/flogo-web/build/server/node_modules/koa/lib/context.js:89:23)
    at Object.flowStart (/tmp/flogo-web/build/server/api/flows.run/index.js:597:15)
    at flowStart.throw (<anonymous>)
    at onRejected (/tmp/flogo-web/build/server/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mellistibco** [comment]
@fcastill can we take a look at this and try to replicate the issue? It looks like the state service may be crashing and the only fix is to restart the container?
