### ISSUE TITLE
Docker image using old version of go

### ISSUE THREAD

**Issue by jezrsmith** [TIBCOSoftware/flogo#58]
I tried to create my first activity using a third party lib but it won't import to the docker image/UI due to:

Activity: https://github.com/jezrsmith/flogo-activities/whatlanggo

[log] Installation results
[1] { success: [], fail: [] }
[1] [log] Build flogo: "flogo build " compileOpts:
[1] [info] run command: flogo build 
[1] [log] command exited with code 1: flogo build 
[1] 2017-08-07T16:31:43.838Z - error:  InternalServerError: # github.com/abadojack/whatlanggo
[1] detect.go:120: undefined: sort.SliceStable
[1] trigrams.go:31: undefined: sort.SliceStable
[1] FATAL: command "build" failed: exit status 2
[1] FATAL: command "build" failed: exit status 1
[1] 
[1]     at Object.module.exports.throw (/tmp/flogo-web/build/server/node_modules/koa/lib/context.js:89:23)
[1]     at Object.<anonymous> (/tmp/flogo-web/build/server/api/error/index.js:41:19)
[1]     at throw (native)
[1]     at Object.dispatch (/tmp/flogo-web/build/server/node_modules/koa-router/lib/router.js:334:12)
[1]     at throw (native)
[1]     at Object.serve (/tmp/flogo-web/build/server/node_modules/koa-static/index.js:43:14)
[1]     at throw (native)
[1]     at Object.compress (/tmp/flogo-web/build/server/node_modules/koa-compress/index.js:42:12)
[1]     at throw (native)
[1]     at onRejected (/tmp/flogo-web/build/server/node_modules/co/index.js:81:24)

On closer inspection it appears this is because sort.SliceStable needs go version 1.8 or later.

Can we get the docker image updated - also is there a way for me to update the version of go on my docker?

**Comment by mellistibco** [comment]
Hi @jezrsmith We'll look at adding this for a future release. As for upgrading yours, you can do this by creating a Docker file and just using flogo-docker as the base.

**Comment by mellistibco** [comment]
This will be resolved in 0.5.2. We've upgraded to Go 1.9.2

**Comment by mellistibco** [comment]
0.5.2 is now using go 1.9
