### ISSUE TITLE
Unable to install custom activity using flogo WebUI

### ISSUE THREAD

**Issue by Ganitagya** [TIBCOSoftware/flogo#59]
Hi Team,

I have successfully created the HelloWorld activity, i.e. ```go test``` returns success.
But when I try to install the activity from Flogo WebUi, I get "install fail" message and the cli shows the below error:
```
[log] Install Activities
[ 'github.com/Ganitagya/Custom_flogo_activity/tree/master/First/HelloWorld' ]
[log] adding activities to test engine...
2017-08-16T09:44:29.087Z - error:  Error: [error] Encounter error to stop test engine.
    at Object.installActivities (/tmp/flogo-web/build/server/api/activities/index.js:131:13)
    at next (native)
    at onFulfilled (/tmp/flogo-web/build/server/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
When I try to use the cli to install the activity, I get the below error:
```
username HelloWorld $ flogo install  github.com/Ganitagya/Custom_flogo_activity/tree/master/First/HelloWorld
FATAL: command "fetch" failed: GetFileAttributesEx C:\Users\username\AppData\Local\Temp\gb-vendor-022114826\tree\master\First\HelloWorld: The system cannot find the path specified.
FATAL: command "vendor" failed: exit status 1
FATAL: command "install" failed: exit status 1
```

I am using the above commands after updating the flogo cli: 
``` go get -u github.com/TIBCOSoftware/flogo-cli/...```

**Comment by mellistibco** [comment]
The URL is wrong, Try: flogo install github.com/Ganitagya/Custom_flogo_activity/First/HelloWorld
